version: '3.7'
services:
  bankdb:
    image: postgres:12.3-alpine
    ports:
      - 5433:5433
    environment:
      POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

